### ISSUE TITLE
网站无法访问，返回404错误

### ISSUE THREAD

**Issue by luoxufeiyan** [hitokoto-osc/hitokoto-developer-docs#66]
开发文档网站 https://developer.hitokoto.cn/ 无法访问，返回404错误

**Comment by greenhat616** [comment]
@du5 @luoxufeiyan 因为 Github Pages 的 CNAME 解析一直掉（因为我用的国内+国外解析），所以我先移除掉 GH 的解析。你们看看速度怎么样，目前是使用腾讯云对象存储服务的。

**Comment by du5** [comment]
> @du5 @luoxufeiyan 因为 Github Pages 的 CNAME 解析一直掉（因为我用的国内+国外解析），所以我先移除掉 GH 的解析。你们看看速度怎么样，目前是使用腾讯云对象存储服务的。

是因为 CNAME 我看提交记录是通过手动添加的，正确做法是放在文档目录里，编译会带过去

**Comment by du5** [comment]
这个和 hexo 编译应该一个逻辑，不过 vue 我不太熟练，我看最新的编译并没有带过去，位置可能还需要调整。

**Comment by du5** [comment]
https://www.zhihu.com/question/28814437
